"""empty message

Revision ID: 1517ab92cfd
Revises: 6af56246c8
Create Date: 2017-07-02 16:19:22.901753

"""

# revision identifiers, used by Alembic.
revision = '1517ab92cfd'
down_revision = '6af56246c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
