"""empty message

Revision ID: 1ab709bcb18
Revises: 56907d79518
Create Date: 2017-06-11 18:59:22.263122

"""

# revision identifiers, used by Alembic.
revision = '1ab709bcb18'
down_revision = '56907d79518'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbtypes',
    sa.Column('db_type_id', sa.Integer(), nullable=False),
    sa.Column('db_type_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('db_type_id'),
    sa.UniqueConstraint('db_type_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbtypes')
    ### end Alembic commands ###
