"""migration v0.1

Revision ID: 1cf17229dc4
Revises: 51f5ccfba190
Create Date: 2017-05-14 16:25:30.902016

"""

# revision identifiers, used by Alembic.
revision = '1cf17229dc4'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbinfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('ip', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('dbname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monilogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_log', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monilogs_timestamp', 'monilogs', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monilogs_timestamp', 'monilogs')
    op.drop_table('monilogs')
    op.drop_table('dbinfos')
    ### end Alembic commands ###
