"""empty message

Revision ID: 3125e3fd49a
Revises: 224f4477e24
Create Date: 2017-09-25 22:22:42.392668

"""

# revision identifiers, used by Alembic.
revision = '3125e3fd49a'
down_revision = '224f4477e24'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_schemas',
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('schame_name', sa.String(length=100), nullable=True),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], ),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.drop_table('schemas')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemas',
    sa.Column('schema_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('schame_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('db_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], name='schemas_ibfk_1'),
    sa.PrimaryKeyConstraint('schema_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('db_schemas')
    ### end Alembic commands ###
