"""empty message

Revision ID: 362c3d17fe8
Revises: 2dd4908bfa6
Create Date: 2017-06-30 14:40:42.105807

"""

# revision identifiers, used by Alembic.
revision = '362c3d17fe8'
down_revision = '2dd4908bfa6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_items', sa.Column('check_name', sa.String(length=100), nullable=True))
    op.drop_column('check_items', 'check_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_items', sa.Column('check_item', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('check_items', 'check_name')
    ### end Alembic commands ###
