"""empty message

Revision ID: 56907d79518
Revises: 38af6f1737e
Create Date: 2017-06-11 18:43:50.321124

"""

# revision identifiers, used by Alembic.
revision = '56907d79518'
down_revision = '38af6f1737e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbtypes',
    sa.Column('db_type_id', sa.Integer(), nullable=False),
    sa.Column('db_type_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('db_type_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbtypes')
    ### end Alembic commands ###
