"""empty message

Revision ID: b6132ac3fa
Revises: 4c2a2b91e0
Create Date: 2017-07-01 23:35:38.303345

"""

# revision identifiers, used by Alembic.
revision = 'b6132ac3fa'
down_revision = '4c2a2b91e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['check_items.check_id'], ),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['alarm_levels.level_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alarm_logs', sa.Column('alarm_log', sa.Text(), nullable=True))
    op.drop_column('alarm_logs', 'monitor_log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_logs', sa.Column('monitor_log', mysql.TEXT(), nullable=True))
    op.drop_column('alarm_logs', 'alarm_log')
    op.drop_table('alarm_thresholds')
    ### end Alembic commands ###
