"""empty message

Revision ID: 1c5f4407ec2
Revises: 348d0b49ec5
Create Date: 2017-09-18 21:57:27.395246

"""

# revision identifiers, used by Alembic.
revision = '1c5f4407ec2'
down_revision = '348d0b49ec5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_addresses',
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('ip_id')
    )
    op.create_table('db_arches',
    sa.Column('db_arch_id', sa.SmallInteger(), nullable=False),
    sa.Column('db_type_id', sa.Integer(), nullable=True),
    sa.Column('db_arch_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['db_type_id'], ['dbtypes.db_type_id'], ),
    sa.PrimaryKeyConstraint('db_arch_id')
    )
    op.create_table('hosts',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('host_name', sa.String(length=100), nullable=True),
    sa.Column('host_ip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_ip_id'], ['ip_addresses.ip_id'], ),
    sa.PrimaryKeyConstraint('host_id')
    )
    op.create_table('inst_roles',
    sa.Column('dbinst_role_id', sa.SmallInteger(), nullable=False),
    sa.Column('db_type_id', sa.Integer(), nullable=True),
    sa.Column('dbinst_role_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['db_type_id'], ['dbtypes.db_type_id'], ),
    sa.PrimaryKeyConstraint('dbinst_role_id')
    )
    op.create_table('instances',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=True),
    sa.Column('access_ip_id', sa.Integer(), nullable=True),
    sa.Column('access_port', sa.Integer(), nullable=True),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_ip_id'], ['ip_addresses.ip_id'], ),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.host_id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('schemas',
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('schame_name', sa.String(length=100), nullable=True),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], ),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.add_column('dbinfos', sa.Column('db_arch_id', sa.Integer(), nullable=True))
    op.drop_column('dbinfos', 'port')
    op.drop_column('dbinfos', 'instance_name')
    op.drop_column('dbinfos', 'schema_name')
    op.drop_column('dbinfos', 'ip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbinfos', sa.Column('ip', mysql.INTEGER(display_width=10, unsigned=True), nullable=True))
    op.add_column('dbinfos', sa.Column('schema_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('dbinfos', sa.Column('instance_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('dbinfos', sa.Column('port', mysql.INTEGER(display_width=11), nullable=True))
    op.drop_column('dbinfos', 'db_arch_id')
    op.drop_table('schemas')
    op.drop_table('instances')
    op.drop_table('inst_roles')
    op.drop_table('hosts')
    op.drop_table('db_arches')
    op.drop_table('ip_addresses')
    ### end Alembic commands ###
