"""empty message

Revision ID: 1c8d9a4510d
Revises: 334c97b7eb0
Create Date: 2017-06-08 23:18:38.546097

"""

# revision identifiers, used by Alembic.
revision = '1c8d9a4510d'
down_revision = '334c97b7eb0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbinfos', 'ip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbinfos', sa.Column('ip', mysql.INTEGER(display_width=10, unsigned=True), nullable=True))
    ### end Alembic commands ###
