"""empty message

Revision ID: 2db65c4cc05
Revises: 3590c75795
Create Date: 2017-06-27 10:24:25.163768

"""

# revision identifiers, used by Alembic.
revision = '2db65c4cc05'
down_revision = '3590c75795'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_connectivity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_connectivity_logs_check_time', 'check_connectivity_logs', ['check_time'], unique=False)
    op.create_table('check_connect_num_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.Column('connect_num', sa.Integer(), nullable=True),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_connect_num_logs_check_time', 'check_connect_num_logs', ['check_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_connect_num_logs_check_time', 'check_connect_num_logs')
    op.drop_table('check_connect_num_logs')
    op.drop_index('ix_check_connectivity_logs_check_time', 'check_connectivity_logs')
    op.drop_table('check_connectivity_logs')
    ### end Alembic commands ###
