"""empty message

Revision ID: 2dd4908bfa6
Revises: 2db65c4cc05
Create Date: 2017-06-28 14:59:40.883155

"""

# revision identifiers, used by Alembic.
revision = '2dd4908bfa6'
down_revision = '2db65c4cc05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_items',
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('check_item', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.SmallInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('check_id')
    )
    op.create_table('alarm_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('alarm_level', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_level'], ['monitor_levels.level_id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['check_items.check_id'], ),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm_thresholds')
    op.drop_table('check_items')
    ### end Alembic commands ###
