"""empty message

Revision ID: 334c97b7eb0
Revises: 3e098259b99
Create Date: 2017-06-08 23:15:46.436293

"""

# revision identifiers, used by Alembic.
revision = '334c97b7eb0'
down_revision = '3e098259b99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
