"""empty message

Revision ID: a57123178a
Revises: 1cf17229dc4
Create Date: 2017-06-08 23:06:16.920132

"""

# revision identifiers, used by Alembic.
revision = '3590c75795'
down_revision = '1ab709bcb18'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbinfos',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('dbname', sa.String(length=100), nullable=True),
    sa.Column('ip', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('instance_name', sa.String(length=100), nullable=True),
    sa.Column('schema_name', sa.String(length=100), nullable=True),
    sa.Column('db_type', sa.String(length=20), nullable=True),
    sa.Column('add_time',sa.DateTime(),nullable=True),
    sa.ForeignKeyConstraint(['db_type'],['dbtypes.db_type_name'],),
    sa.PrimaryKeyConstraint('db_id')
    )
    op.create_index('ix_dbinfos_add_time','dbinfos',['add_time'],unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dbinfos_add_time', 'dbinfos')

    ### end Alembic commands ###
