"""empty message

Revision ID: 3e098259b99
Revises: a57123178a
Create Date: 2017-06-08 23:12:32.139855

"""

# revision identifiers, used by Alembic.
revision = '3e098259b99'
down_revision = 'a57123178a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
