"""empty message

Revision ID: 48d6e42fd6
Revises: b6132ac3fa
Create Date: 2017-07-02 10:38:03.694928

"""

# revision identifiers, used by Alembic.
revision = '48d6e42fd6'
down_revision = 'b6132ac3fa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_logs', sa.Column('alarm_message', sa.Text(), nullable=True))
    op.drop_column('alarm_logs', 'alarm_log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_logs', sa.Column('alarm_log', mysql.TEXT(), nullable=True))
    op.drop_column('alarm_logs', 'alarm_message')
    ### end Alembic commands ###
