"""empty message

Revision ID: 4c2a2b91e0
Revises: 362c3d17fe8
Create Date: 2017-07-01 18:56:53.225477

"""

# revision identifiers, used by Alembic.
revision = '4c2a2b91e0'
down_revision = '362c3d17fe8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=20), nullable=True),
    sa.Column('level_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('alarm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_id', sa.Integer(), nullable=True),
    sa.Column('monitor_log', sa.Text(), nullable=True),
    sa.Column('level_name', sa.String(length=20), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['check_items.check_id'], ),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['alarm_levels.level_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alarm_logs_create_time', 'alarm_logs', ['create_time'], unique=False)
    op.drop_table('monitor_logs')
    op.drop_table('monitor_levels')
    op.add_column('check_connect_num_logs', sa.Column('max_num', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_connect_num_logs', 'max_num')
    op.create_table('monitor_levels',
    sa.Column('level_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('level_name', mysql.TEXT(), nullable=True),
    sa.Column('level_desc', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('level_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('monitor_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('db_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('monitor_log', mysql.TEXT(), nullable=True),
    sa.Column('monitor_level', mysql.TEXT(), nullable=True),
    sa.Column('level_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('finish_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['dbinfos.db_id'], name='monitor_logs_ibfk_1'),
    sa.ForeignKeyConstraint(['level_id'], ['monitor_levels.level_id'], name='monitor_logs_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index('ix_alarm_logs_create_time', 'alarm_logs')
    op.drop_table('alarm_logs')
    op.drop_table('alarm_levels')
    ### end Alembic commands ###
