"""empty message

Revision ID: 6af56246c8
Revises: 48d6e42fd6
Create Date: 2017-07-02 15:35:12.631994

"""

# revision identifiers, used by Alembic.
revision = '6af56246c8'
down_revision = '48d6e42fd6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbinfos', sa.Column('db_type_id', sa.String(length=20), nullable=True))
    op.drop_column('dbinfos', 'db_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbinfos', sa.Column('db_type', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('dbinfos', 'db_type_id')
    ### end Alembic commands ###
